# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import blog_pb2 as blog__pb2


class BlogStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateBlog = channel.unary_unary(
        '/blog.Blog/CreateBlog',
        request_serializer=blog__pb2.BlogCreationObject.SerializeToString,
        response_deserializer=blog__pb2.BlogCreationResponse.FromString,
        )
    self.BlogListing = channel.unary_unary(
        '/blog.Blog/BlogListing',
        request_serializer=blog__pb2.BlogListingRequest.SerializeToString,
        response_deserializer=blog__pb2.BlogListingResponse.FromString,
        )


class BlogServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateBlog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogListing(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BlogServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateBlog': grpc.unary_unary_rpc_method_handler(
          servicer.CreateBlog,
          request_deserializer=blog__pb2.BlogCreationObject.FromString,
          response_serializer=blog__pb2.BlogCreationResponse.SerializeToString,
      ),
      'BlogListing': grpc.unary_unary_rpc_method_handler(
          servicer.BlogListing,
          request_deserializer=blog__pb2.BlogListingRequest.FromString,
          response_serializer=blog__pb2.BlogListingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'blog.Blog', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
