# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blog.proto',
  package='blog',
  syntax='proto3',
  serialized_pb=_b('\n\nblog.proto\x12\x04\x62log\"W\n\x12\x42logCreationObject\x12\r\n\x05Title\x18\x01 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x02 \x01(\t\x12\x0e\n\x06\x41uthor\x18\x03 \x01(\t\x12\x11\n\tCreatedAt\x18\x04 \x01(\t\">\n\x14\x42logCreationResponse\x12\x18\n\x04meta\x18\x01 \x01(\x0b\x32\n.blog.Meta\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"M\n\x13\x42logListingResponse\x12\x18\n\x04meta\x18\x01 \x01(\x0b\x32\n.blog.Meta\x12\x1c\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x0e.blog.Response\":\n\x08Response\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"#\n\x12\x42logListingRequest\x12\r\n\x05Title\x18\x01 \x01(\t\"6\n\x04Meta\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x32\x92\x01\n\x04\x42log\x12\x44\n\nCreateBlog\x12\x18.blog.BlogCreationObject\x1a\x1a.blog.BlogCreationResponse\"\x00\x12\x44\n\x0b\x42logListing\x12\x18.blog.BlogListingRequest\x1a\x19.blog.BlogListingResponse\"\x00\x62\x06proto3')
)




_BLOGCREATIONOBJECT = _descriptor.Descriptor(
  name='BlogCreationObject',
  full_name='blog.BlogCreationObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Title', full_name='blog.BlogCreationObject.Title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='blog.BlogCreationObject.Content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Author', full_name='blog.BlogCreationObject.Author', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CreatedAt', full_name='blog.BlogCreationObject.CreatedAt', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=107,
)


_BLOGCREATIONRESPONSE = _descriptor.Descriptor(
  name='BlogCreationResponse',
  full_name='blog.BlogCreationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='blog.BlogCreationResponse.meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='blog.BlogCreationResponse.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=171,
)


_BLOGLISTINGRESPONSE = _descriptor.Descriptor(
  name='BlogListingResponse',
  full_name='blog.BlogListingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='blog.BlogListingResponse.meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='blog.BlogListingResponse.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=250,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='blog.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='blog.Response.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='blog.Response.author', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='blog.Response.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=310,
)


_BLOGLISTINGREQUEST = _descriptor.Descriptor(
  name='BlogListingRequest',
  full_name='blog.BlogListingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Title', full_name='blog.BlogListingRequest.Title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=347,
)


_META = _descriptor.Descriptor(
  name='Meta',
  full_name='blog.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='blog.Meta.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='blog.Meta.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='blog.Meta.code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=403,
)

_BLOGCREATIONRESPONSE.fields_by_name['meta'].message_type = _META
_BLOGLISTINGRESPONSE.fields_by_name['meta'].message_type = _META
_BLOGLISTINGRESPONSE.fields_by_name['data'].message_type = _RESPONSE
DESCRIPTOR.message_types_by_name['BlogCreationObject'] = _BLOGCREATIONOBJECT
DESCRIPTOR.message_types_by_name['BlogCreationResponse'] = _BLOGCREATIONRESPONSE
DESCRIPTOR.message_types_by_name['BlogListingResponse'] = _BLOGLISTINGRESPONSE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['BlogListingRequest'] = _BLOGLISTINGREQUEST
DESCRIPTOR.message_types_by_name['Meta'] = _META
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlogCreationObject = _reflection.GeneratedProtocolMessageType('BlogCreationObject', (_message.Message,), dict(
  DESCRIPTOR = _BLOGCREATIONOBJECT,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.BlogCreationObject)
  ))
_sym_db.RegisterMessage(BlogCreationObject)

BlogCreationResponse = _reflection.GeneratedProtocolMessageType('BlogCreationResponse', (_message.Message,), dict(
  DESCRIPTOR = _BLOGCREATIONRESPONSE,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.BlogCreationResponse)
  ))
_sym_db.RegisterMessage(BlogCreationResponse)

BlogListingResponse = _reflection.GeneratedProtocolMessageType('BlogListingResponse', (_message.Message,), dict(
  DESCRIPTOR = _BLOGLISTINGRESPONSE,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.BlogListingResponse)
  ))
_sym_db.RegisterMessage(BlogListingResponse)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.Response)
  ))
_sym_db.RegisterMessage(Response)

BlogListingRequest = _reflection.GeneratedProtocolMessageType('BlogListingRequest', (_message.Message,), dict(
  DESCRIPTOR = _BLOGLISTINGREQUEST,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.BlogListingRequest)
  ))
_sym_db.RegisterMessage(BlogListingRequest)

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(
  DESCRIPTOR = _META,
  __module__ = 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.Meta)
  ))
_sym_db.RegisterMessage(Meta)



_BLOG = _descriptor.ServiceDescriptor(
  name='Blog',
  full_name='blog.Blog',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=406,
  serialized_end=552,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateBlog',
    full_name='blog.Blog.CreateBlog',
    index=0,
    containing_service=None,
    input_type=_BLOGCREATIONOBJECT,
    output_type=_BLOGCREATIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BlogListing',
    full_name='blog.Blog.BlogListing',
    index=1,
    containing_service=None,
    input_type=_BLOGLISTINGREQUEST,
    output_type=_BLOGLISTINGRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOG)

DESCRIPTOR.services_by_name['Blog'] = _BLOG

# @@protoc_insertion_point(module_scope)
